# Generated by Django 4.2 on 2023-04-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='desciption',
            new_name='description',
        ),
    ]
